apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "kubecost.fullname" . }}
  labels:
    app: {{ include "kubecost.name" . }}
    chart: {{ include "kubecost.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "kubecost.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ include "kubecost.name" . }}
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 9090
          resources:
            {{- toYaml .Values.resources | nindent 12 }}

